version: "3.3"

services:
    postgres:
        image: 'postgres'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'        
        ports:
            - "5432:5432"

    phoenix:  
        build: 
            context: .
        environment:
            DATABASE_URL: ecto://postgres:postgres@db/postgres
            DATABASE_USER: postgres
            DATABASE_PASS: postgres
            DATABASE_NAME: postgres
            DATABASE_PORT: 5432
            DATABASE_HOST: postgres
            MIX_ENV: dev
        depends_on:
            - postgres
        ports:
            - "4000:4000"  
        
         
